const creditCardData: CreditCard[] = [
	{
		id: 1,
		name: "Chase Sapphire Preferred",
		issuer: "Chase",
		rewardType: "",
		annualFee: 95.0,
		signUpBonus: "Excellent credit, $5k min limit",
		earningRate: "2x travel/dining, 50k bonus",
		bonusCategories: "Transferrable points",
		foreignTransactionFees: "",
		interestRate: 0,
	},
	{
		id: 2,
		name: "Citi Double Cash",
		issuer: "Citi",
		rewardType: "",
		annualFee: 0.0,
		signUpBonus: "Good credit",
		earningRate: "2% cash back",
		bonusCategories: "Flat-rate cash back",
		foreignTransactionFees: "",
		interestRate: 0,
	},
	{
		id: 3,
		name: "Capital One Savor",
		issuer: "Capital One",
		rewardType: "",
		annualFee: 95.0,
		signUpBonus: "Good credit",
		earningRate: "4% dining, 2% groceries",
		bonusCategories: "Cash back rewards",
		foreignTransactionFees: "",
		interestRate: 0,
	},
	{
		id: 4,
		name: "Amex Gold",
		issuer: "Amex",
		rewardType: "",
		annualFee: 250.0,
		signUpBonus: "Good credit, annual fee",
		earningRate: "4x restaurants, 3x flights",
		bonusCategories: "Great for dining/flights",
		foreignTransactionFees: "",
		interestRate: 0,
	},
	{
		id: 5,
		name: "Wells Fargo Propel",
		issuer: "Wells Fargo",
		rewardType: "",
		annualFee: 0.0,
		signUpBonus: "Good to excellent credit",
		earningRate: "3x travel/dining/gas/transit",
		bonusCategories: "Transferrable points",
		foreignTransactionFees: "",
		interestRate: 0,
	},
	{
		id: 6,
		name: "BofA Travel Rewards",
		issuer: "BofA",
		rewardType: "",
		annualFee: 0.0,
		signUpBonus: "Good credit",
		earningRate: "1.5x all purchases",
		bonusCategories: "Travel statement credits",
		foreignTransactionFees: "",
		interestRate: 0,
	},
	{
		id: 7,
		name: "Chase Freedom Unlimited",
		issuer: "Chase",
		rewardType: "",
		annualFee: 0.0,
		signUpBonus: "Good credit",
		earningRate: "1.5% cash back",
		bonusCategories: "Transferrable cash back",
		foreignTransactionFees: "",
		interestRate: 0,
	},
	{
		id: 8,
		name: "Discover it Miles",
		issuer: "Discover",
		rewardType: "",
		annualFee: 0.0,
		signUpBonus: "Good credit",
		earningRate: "1.5x miles all purchases",
		bonusCategories: "Travel/cash redemptions",
		foreignTransactionFees: "",
		interestRate: 0,
	},
	{
		id: 9,
		name: "Costco Anywhere Visa",
		issuer: "Citi",
		rewardType: "",
		annualFee: 0.0,
		signUpBonus: "Costco membership",
		earningRate: "4% gas, 3% travel/dining",
		bonusCategories: "Costco membership required",
		foreignTransactionFees: "",
		interestRate: 0,
	},
	{
		id: 10,
		name: "Amex",
		issuer: "Amex",
		rewardType: "",
		annualFee: 450.0,
		signUpBonus: "Excellent credit, $450 fee",
		earningRate: "14x Hilton, 7x flights",
		bonusCategories: "Top tier Hilton card",
		foreignTransactionFees: "",
		interestRate: 0,
	},
	{
		id: 11,
		name: "Chase Sapphire Reserve",
		issuer: "Chase",
		rewardType: "",
		annualFee: 550.0,
		signUpBonus: "Excellent credit, $10k min limit",
		earningRate: "3x travel/dining, $300 credit",
		bonusCategories: "Premium travel perks",
		foreignTransactionFees: "",
		interestRate: 0,
	},
	{
		id: 12,
		name: "Capital One Venture X",
		issuer: "Capital One",
		rewardType: "",
		annualFee: 395.0,
		signUpBonus: "Good to excellent credit, $395 fee",
		earningRate: "2x all purchases",
		bonusCategories: "Transferrable miles",
		foreignTransactionFees: "",
		interestRate: 0,
	},
	{
		id: 13,
		name: "Amex Platinum",
		issuer: "Amex",
		rewardType: "",
		annualFee: 695.0,
		signUpBonus: "Good to excellent credit, $695 fee",
		earningRate: "5x flights, lounge access",
		bonusCategories: "Luxury card, metal design",
		foreignTransactionFees: "",
		interestRate: 0,
	},
	{
		id: 14,
		name: "Citi Premier",
		issuer: "Citi",
		rewardType: "",
		annualFee: 95.0,
		signUpBonus: "Good credit, $95 fee",
		earningRate: "3x travel, gas, dining",
		bonusCategories: "Transferrable points",
		foreignTransactionFees: "",
		interestRate: 0,
	},
	{
		id: 15,
		name: "Southwest Priority",
		issuer: "Chase",
		rewardType: "",
		annualFee: 149.0,
		signUpBonus: "Good credit, $149 fee",
		earningRate: "2x Southwest purchases",
		bonusCategories: "Southwest Companion Pass eligible",
		foreignTransactionFees: "",
		interestRate: 0,
	},
	{
		id: 16,
		name: "Hilton Honors American Express Surpass",
		issuer: "Amex",
		rewardType: "",
		annualFee: 95.0,
		signUpBonus: "Good credit, $95 fee",
		earningRate: "12x Hilton, 6x dining/groceries/gas",
		bonusCategories: "Free weekend night reward",
		foreignTransactionFees: "",
		interestRate: 0,
	},
	{
		id: 17,
		name: "Marriott Bonvoy Boundless",
		issuer: "Chase",
		rewardType: "",
		annualFee: 95.0,
		signUpBonus: "Good credit, $95 fee",
		earningRate: "3x Marriott, 2x dining/gas",
		bonusCategories: "Free anniversary night",
		foreignTransactionFees: "",
		interestRate: 0,
	},
	{
		id: 18,
		name: "Hilton Honors",
		issuer: "Amex",
		rewardType: "",
		annualFee: 0.0,
		signUpBonus: "Good credit",
		earningRate: "7x Hilton, 5x airfare/dining",
		bonusCategories: "No annual fee Hilton card",
		foreignTransactionFees: "",
		interestRate: 0,
	},
	{
		id: 19,
		name: "Delta SkyMiles Reserve American Express",
		issuer: "Amex",
		rewardType: "",
		annualFee: 550.0,
		signUpBonus: "Good credit, $550 fee",
		earningRate: "3x Delta, Centurion lounge access",
		bonusCategories: "Premium Delta card",
		foreignTransactionFees: "",
		interestRate: 0,
	},
	{
		id: 20,
		name: "Delta SkyMiles Platinum American Express",
		issuer: "Amex",
		rewardType: "",
		annualFee: 250.0,
		signUpBonus: "Good credit, $250 fee",
		earningRate: "3x Delta, annual companion fare",
		bonusCategories: "Mid-tier Delta card",
		foreignTransactionFees: "",
		interestRate: 0,
	},
	{
		id: 21,
		name: "Delta SkyMiles Blue American Express",
		issuer: "Amex",
		rewardType: "",
		annualFee: 0.0,
		signUpBonus: "Good credit",
		earningRate: "2x Delta",
		bonusCategories: "No annual fee Delta card",
		foreignTransactionFees: "",
		interestRate: 0,
	},
	{
		id: 22,
		name: "United Explorer Card",
		issuer: "Chase",
		rewardType: "",
		annualFee: 95.0,
		signUpBonus: "Good credit, $95 fee",
		earningRate: "2x United, 2x dining/hotel",
		bonusCategories: "Free checked bag, priority boarding",
		foreignTransactionFees: "",
		interestRate: 0,
	},
	{
		id: 23,
		name: "IHG Rewards Premier",
		issuer: "Chase",
		rewardType: "",
		annualFee: 99.0,
		signUpBonus: "Good credit, $99 fee",
		earningRate: "25x IHG, 2x gas/dining/groceries",
		bonusCategories: "Anniversary free night",
		foreignTransactionFees: "",
		interestRate: 0,
	},
	{
		id: 24,
		name: "Wyndham Rewards Earner Plus",
		issuer: "Barclays",
		rewardType: "",
		annualFee: 75.0,
		signUpBonus: "Good credit, $75 fee",
		earningRate: "5x Wyndham, grocery/gas/utility",
		bonusCategories: "Anniversary free night",
		foreignTransactionFees: "",
		interestRate: 0,
	},
	{
		id: 25,
		name: "World of Hyatt Credit Card",
		issuer: "Chase",
		rewardType: "",
		annualFee: 95.0,
		signUpBonus: "Good credit, $95 fee",
		earningRate: "4x Hyatt, dining/flights/rentals/transit",
		bonusCategories: "Anniversary free night",
		foreignTransactionFees: "",
		interestRate: 0,
	},
	{
		id: 26,
		name: "Radisson Rewards Premier Visa Signature",
		issuer: "BofA",
		rewardType: "",
		annualFee: 75.0,
		signUpBonus: "Good credit, $75 fee",
		earningRate: "10x Radisson, 6x groceries/gas",
		bonusCategories: "Anniversary free night",
		foreignTransactionFees: "",
		interestRate: 0,
	},
	{
		id: 27,
		name: "Blue Cash Preferred Card from American Express",
		issuer: "Amex",
		rewardType: "",
		annualFee: 95.0,
		signUpBonus: "Good credit, $95 fee",
		earningRate: "6% groceries, streaming",
		bonusCategories: "Popular cash back card",
		foreignTransactionFees: "",
		interestRate: 0,
	},
	{
		id: 28,
		name: "Capital One SavorOne",
		issuer: "Capital One",
		rewardType: "",
		annualFee: 0.0,
		signUpBonus: "Good credit",
		earningRate: "3% dining/entertainment",
		bonusCategories: "No annual fee version of Savor",
		foreignTransactionFees: "",
		interestRate: 0,
	},
	{
		id: 29,
		name: "Amex EveryDay Credit Card",
		issuer: "Amex",
		rewardType: "",
		annualFee: 0.0,
		signUpBonus: "Good credit",
		earningRate: "2x groceries, bonus for frequent use",
		bonusCategories: "Use perks with no annual fee",
		foreignTransactionFees: "",
		interestRate: 0,
	},
	{
		id: 30,
		name: "Bank of America Customized Cash Rewards",
		issuer: "BofA",
		rewardType: "",
		annualFee: 0.0,
		signUpBonus: "Good credit",
		earningRate: "3% category of choice",
		bonusCategories: "Customer-chosen rewards",
		foreignTransactionFees: "",
		interestRate: 0,
	},
	{
		id: 31,
		name: "Chase Freedom Flex",
		issuer: "Chase",
		rewardType: "",
		annualFee: 0.0,
		signUpBonus: "Good credit",
		earningRate: "5% rotating categories",
		bonusCategories: "Rotating quarterly categories",
		foreignTransactionFees: "",
		interestRate: 0,
	},
	{
		id: 32,
		name: "Citi Double Cash Card",
		issuer: "Citi",
		rewardType: "",
		annualFee: 0.0,
		signUpBonus: "Good credit",
		earningRate: "2% cash back",
		bonusCategories: "Flat-rate cash back",
		foreignTransactionFees: "",
		interestRate: 0,
	},
	{
		id: 33,
		name: "Fidelity Rewards Visa Signature",
		issuer: "Fidelity",
		rewardType: "",
		annualFee: 0.0,
		signUpBonus: "Good credit",
		earningRate: "2% cash back into Fidelity account",
		bonusCategories: "Rewards deposited into investment account",
		foreignTransactionFees: "",
		interestRate: 0,
	},
	{
		id: 34,
		name: "Wells Fargo Active Cash Card",
		issuer: "Wells Fargo",
		rewardType: "",
		annualFee: 0.0,
		signUpBonus: "Good credit",
		earningRate: "2% cash back on purchases",
		bonusCategories: "Flat-rate cash back",
		foreignTransactionFees: "",
		interestRate: 0,
	},
	{
		id: 35,
		name: "Chase Freedom Student Credit Card",
		issuer: "Chase",
		rewardType: "",
		annualFee: 0.0,
		signUpBonus: "Good credit for student card",
		earningRate: "1% cash back",
		bonusCategories: "Cash back for students",
		foreignTransactionFees: "",
		interestRate: 0,
	},
	{
		id: 36,
		name: "Discover it Student Cash Back",
		issuer: "Discover",
		rewardType: "",
		annualFee: 0.0,
		signUpBonus: "Good credit for student card",
		earningRate: "1% cash back",
		bonusCategories: "Cash back for students",
		foreignTransactionFees: "",
		interestRate: 0,
	},
	{
		id: 37,
		name: "Deserve Pro Mastercard",
		issuer: "Deserve",
		rewardType: "",
		annualFee: 99.0,
		signUpBonus: "No credit check, for building credit",
		earningRate: "3% dining, travel, subscriptions",
		bonusCategories: "For building credit",
		foreignTransactionFees: "",
		interestRate: 0,
	},
	{
		id: 38,
		name: "Petal 1 Visa Credit Card",
		issuer: "Petal",
		rewardType: "",
		annualFee: 0.0,
		signUpBonus: "No credit check, for building credit",
		earningRate: "1% cash back, credit builder",
		bonusCategories: "Reports to credit bureaus",
		foreignTransactionFees: "",
		interestRate: 0,
	},
	{
		id: 39,
		name: "Capital One Platinum Credit Card",
		issuer: "Capital One",
		rewardType: "",
		annualFee: 0.0,
		signUpBonus: "Average credit",
		earningRate: "1% cash back",
		bonusCategories: "Basic, no frills card",
		foreignTransactionFees: "",
		interestRate: 0,
	},
	{
		id: 40,
		name: "Credit One Bank Platinum Visa",
		issuer: "Credit One",
		rewardType: "",
		annualFee: "$75-99",
		signUpBonus: "Poor to average credit",
		earningRate: "1% cash back",
		bonusCategories: "For rebuilding credit",
		foreignTransactionFees: "",
		interestRate: 0,
	},
	{
		id: 41,
		name: "Surge Mastercard",
		issuer: "First Progress",
		rewardType: "",
		annualFee: "$75-99",
		signUpBonus: "Poor to average credit",
		earningRate: "1% cash back",
		bonusCategories: "For rebuilding credit",
		foreignTransactionFees: "",
		interestRate: 0,
	},
	{
		id: 42,
		name: "Discover it Secured Credit Card",
		issuer: "Discover",
		rewardType: "",
		annualFee: 0.0,
		signUpBonus: "Security deposit required",
		earningRate: "2% cash back",
		bonusCategories: "Secured card for building credit",
		foreignTransactionFees: "",
		interestRate: 0,
	},
	{
		id: 43,
		name: "Capital One QuicksilverOne Cash Rewards",
		issuer: "Capital One",
		rewardType: "",
		annualFee: 39.0,
		signUpBonus: "Average credit",
		earningRate: "1.5% cash back",
		bonusCategories: "Rebuilding card",
		foreignTransactionFees: "",
		interestRate: 0,
	},
	{
		id: 44,
		name: "Merrick Bank Double Your Line Credit Card",
		issuer: "Merrick Bank",
		rewardType: "",
		annualFee: 36.0,
		signUpBonus: "Below average credit",
		earningRate: "None",
		bonusCategories: "Small credit line to build credit",
		foreignTransactionFees: "",
		interestRate: 0,
	},
	{
		id: 45,
		name: "Credit One Bank Unsecured Visa",
		issuer: "Credit One",
		rewardType: "",
		annualFee: 75.0,
		signUpBonus: "Poor credit",
		earningRate: "1% cash back",
		bonusCategories: "Unsecured card for rebuilding credit",
		foreignTransactionFees: "",
		interestRate: 0,
	},
	{
		id: 46,
		name: "First Progress Platinum Prestige Mastercard",
		issuer: "First Progress",
		rewardType: "",
		annualFee: 99.0,
		signUpBonus: "Poor credit",
		earningRate: "None",
		bonusCategories: "Rebuilding card",
		foreignTransactionFees: "",
		interestRate: 0,
	},
	{
		id: 47,
		name: "Indigo Platinum Mastercard",
		issuer: "Celtic Bank",
		rewardType: "",
		annualFee: 75.0,
		signUpBonus: "Poor credit",
		earningRate: "None",
		bonusCategories: "Rebuilding card",
		foreignTransactionFees: "",
		interestRate: 0,
	},
	{
		id: 48,
		name: "FortuneCard Mastercard",
		issuer: "The Bank of Missouri",
		rewardType: "",
		annualFee: 75.0,
		signUpBonus: "Poor credit",
		earningRate: "None",
		bonusCategories: "Rebuilding card",
		foreignTransactionFees: "",
		interestRate: 0,
	},
	{
		id: 49,
		name: "Surge Chrome Visa Credit Card",
		issuer: "Continental Finance",
		rewardType: "",
		annualFee: 99.0,
		signUpBonus: "Poor to fair credit",
		earningRate: "None",
		bonusCategories: "Rebuilding card",
		foreignTransactionFees: "",
		interestRate: 0,
	},
	{
		id: 50,
		name: "First Access Visa Credit Card",
		issuer: "First Access",
		rewardType: "",
		annualFee: 75.0,
		signUpBonus: "Poor credit",
		earningRate: "None",
		bonusCategories: "Rebuilding card",
		foreignTransactionFees: "",
		interestRate: 0,
	},
	{
		id: 51,
		name: "Milestone Gold Mastercard",
		issuer: "Genesis FS Card Services",
		rewardType: "",
		annualFee: "$35-99",
		signUpBonus: "Poor credit",
		earningRate: "None",
		bonusCategories: "Rebuilding card",
		foreignTransactionFees: "",
		interestRate: 0,
	},
	{
		id: 52,
		name: "PenFed Power Cash Rewards Visa Signature",
		issuer: "PenFed",
		rewardType: "",
		annualFee: 0.0,
		signUpBonus: "Good credit, PenFed member",
		earningRate: "2% cash back on all purchases",
		bonusCategories: "Straightforward 2% cash back",
		foreignTransactionFees: "",
		interestRate: 0,
	},
	{
		id: 53,
		name: "PayPal Cashback Mastercard",
		issuer: "Synchrony",
		rewardType: "",
		annualFee: 0.0,
		signUpBonus: "Good credit",
		earningRate: "2% cash back on all purchases",
		bonusCategories: "Can redeem rewards into PayPal account",
		foreignTransactionFees: "",
		interestRate: 0,
	},
	{
		id: 54,
		name: "PenFed Platinum Rewards Visa Signature",
		issuer: "PenFed",
		rewardType: "",
		annualFee: 0.0,
		signUpBonus: "Good credit, PenFed member",
		earningRate: "5x points on PenFed purchases",
		bonusCategories: "Rewards points redeemable for cash",
		foreignTransactionFees: "",
		interestRate: 0,
	},
	{
		id: 55,
		name: "CareCredit Rewards Mastercard",
		issuer: "Synchrony",
		rewardType: "",
		annualFee: 0.0,
		signUpBonus: "Good credit",
		earningRate: "3% back on groceries, gas, & care credit purchases",
		bonusCategories: "For healthcare and wellness expenses",
		foreignTransactionFees: "",
		interestRate: 0,
	},
	{
		id: 56,
		name: "TD Double Up Visa Credit Card",
		issuer: "TD Bank",
		rewardType: "",
		annualFee: 0.0,
		signUpBonus: "Good credit",
		earningRate: "2% cash back at grocery stores",
		bonusCategories: "Earn cash back at grocery stores",
		foreignTransactionFees: "",
		interestRate: 0,
	},
	{
		id: 57,
		name: "TD First Class Visa Signature Credit Card",
		issuer: "TD Bank",
		rewardType: "",
		annualFee: 89.0,
		signUpBonus: "Excellent credit",
		earningRate: "6% cash back at grocery stores",
		bonusCategories: "Higher earn rate for grocery shopping",
		foreignTransactionFees: "",
		interestRate: 0,
	},
	{
		id: 58,
		name: "Chase Ink Business Cash Credit Card",
		issuer: "Chase",
		rewardType: "",
		annualFee: 0.0,
		signUpBonus: "Good credit, business card",
		earningRate: "5% back on office supply stores",
		bonusCategories: "Useful for small business owners",
		foreignTransactionFees: "",
		interestRate: 0,
	},
	{
		id: 59,
		name: "Capital One Spark Cash Plus",
		issuer: "Capital One",
		rewardType: "",
		annualFee: 150.0,
		signUpBonus: "Good credit, business card",
		earningRate: "2% cash back on all purchases",
		bonusCategories: "Flat-rate business card",
		foreignTransactionFees: "",
		interestRate: 0,
	},
	{
		id: 60,
		name: "Brex Corporate Card for Startups",
		issuer: "Brex",
		rewardType: "",
		annualFee: 0.0,
		signUpBonus: "Business application required",
		earningRate: "No rewards program",
		bonusCategories: "Corporate charge card for business expenses",
		foreignTransactionFees: "",
		interestRate: 0,
	},
	{
		id: 61,
		name: "U.S. Bank Business Leverage Visa Card",
		issuer: "U.S. Bank",
		rewardType: "",
		annualFee: 100.0,
		signUpBonus: "Good credit, business card",
		earningRate: "5% cash back on office supply stores and cell phone plans",
		bonusCategories: "Category rewards for businesses",
		foreignTransactionFees: "",
		interestRate: 0,
	},
	{
		id: 62,
		name: "Deserve Edu Mastercard for Students",
		issuer: "Deserve",
		rewardType: "",
		annualFee: 0.0,
		signUpBonus: "No credit check",
		earningRate: "3% travel, 1% everywhere",
		bonusCategories: "For international students studying in the U.S.",
		foreignTransactionFees: "",
		interestRate: 0,
	},
	{
		id: 63,
		name: "Discover Global Network Card",
		issuer: "Discover",
		rewardType: "",
		annualFee: 0.0,
		signUpBonus: "International travel",
		earningRate: "None",
		bonusCategories: "Accepted worldwide",
		foreignTransactionFees: "",
		interestRate: 0,
	},
	{
		id: 64,
		name: "HSBC Premier World Elite Mastercard",
		issuer: "HSBC",
		rewardType: "",
		annualFee: 395.0,
		signUpBonus: "Premier checking account required",
		earningRate: "3x travel & dining",
		bonusCategories: "Luxury card with rewards",
		foreignTransactionFees: "",
		interestRate: 0,
	},
	{
		id: 65,
		name: "Aeromexico Visa Business",
		issuer: "Banorte USA",
		rewardType: "",
		annualFee: 149.0,
		signUpBonus: "Good credit, business card",
		earningRate: "3x Aeromexico purchases",
		bonusCategories: "Airline co-brand business card",
		foreignTransactionFees: "",
		interestRate: 0,
	},
	{
		id: 66,
		name: "Cathay Pacific Visa Business Card",
		issuer: "Banco Popular",
		rewardType: "",
		annualFee: 95.0,
		signUpBonus: "Good credit, business card",
		earningRate: "3x Cathay Pacific purchases",
		bonusCategories: "Airline co-brand business card",
		foreignTransactionFees: "",
		interestRate: 0,
	},
	{
		id: 67,
		name: "Turkish Airlines Elite Visa Business Card",
		issuer: "Citi",
		rewardType: "",
		annualFee: 20.0,
		signUpBonus: "000 miles annual fee",
		earningRate: "2x Turkish Airlines purchases",
		bonusCategories: "Good credit, business card, Airline co-brand business card",
		foreignTransactionFees: "",
		interestRate: 0,
	},
	{
		id: 68,
		name: "Southwest Rapid Rewards Premier Business Credit Card",
		issuer: "Chase",
		rewardType: "",
		annualFee: 99.0,
		signUpBonus: "Good credit, business card",
		earningRate: "2x Southwest purchases",
		bonusCategories: "Airline business card",
		foreignTransactionFees: "",
		interestRate: 0,
	},
	{
		id: 69,
		name: "United Business Card",
		issuer: "Chase",
		rewardType: "",
		annualFee: 99.0,
		signUpBonus: "Good credit, business card",
		earningRate: "2x United purchases",
		bonusCategories: "Airline business card",
		foreignTransactionFees: "",
		interestRate: 0,
	},
	{
		id: 70,
		name: "Delta SkyMiles Platinum Business American Express Card",
		issuer: "Amex",
		rewardType: "",
		annualFee: 250.0,
		signUpBonus: "Good credit, business card",
		earningRate: "2x Delta purchases",
		bonusCategories: "Airline business card",
		foreignTransactionFees: "",
		interestRate: 0,
	},
	{
		id: 71,
		name: "American Express Business Gold Card",
		issuer: "Amex",
		rewardType: "",
		annualFee: 295.0,
		signUpBonus: "Good credit, business card",
		earningRate: "4x major spend categories",
		bonusCategories: "Flexible business card",
		foreignTransactionFees: "",
		interestRate: 0,
	},
	{
		id: 72,
		name: "Ink Business Preferred Credit Card",
		issuer: "Chase",
		rewardType: "",
		annualFee: 95.0,
		signUpBonus: "Good credit, business card",
		earningRate: "3x travel, shipping, internet/cable/phone",
		bonusCategories: "Broad 3x categories",
		foreignTransactionFees: "",
		interestRate: 0,
	},
	{
		id: 73,
		name: "Capital One Spark Miles Business Credit Card",
		issuer: "Capital One",
		rewardType: "",
		annualFee: 95.0,
		signUpBonus: "Good credit, business card",
		earningRate: "2x all purchases",
		bonusCategories: "Simple flat-rate business card",
		foreignTransactionFees: "",
		interestRate: 0,
	},
	{
		id: 74,
		name: "Blue Business Plus Credit Card from American Express",
		issuer: "Amex",
		rewardType: "",
		annualFee: 0.0,
		signUpBonus: "Good credit, business card",
		earningRate: "2x all purchases",
		bonusCategories: "No annual fee business card",
		foreignTransactionFees: "",
		interestRate: 0,
	},
	{
		id: 75,
		name: "Wells Fargo Business Platinum Credit Card",
		issuer: "Wells Fargo",
		rewardType: "",
		annualFee: 0.0,
		signUpBonus: "Good credit, business card",
		earningRate: "1.5% cash back",
		bonusCategories: "Cash back business card",
		foreignTransactionFees: "",
		interestRate: 0,
	},
	{
		id: 76,
		name: "Capital One Spark Cash Select Business Credit Card",
		issuer: "Capital One",
		rewardType: "",
		annualFee: 0.0,
		signUpBonus: "Good credit, business card",
		earningRate: "1.5% cash back",
		bonusCategories: "Cash back business card",
		foreignTransactionFees: "",
		interestRate: 0,
	},
	{
		id: 77,
		name: "The Business Platinum Card from American Express",
		issuer: "Amex",
		rewardType: "",
		annualFee: 695.0,
		signUpBonus: "Excellent credit, business card",
		earningRate: "5x flights and hotels",
		bonusCategories: "High-end premium business card",
		foreignTransactionFees: "",
		interestRate: 0,
	},
	{
		id: 78,
		name: "Ink Business Unlimited Credit Card",
		issuer: "Chase",
		rewardType: "",
		annualFee: 0.0,
		signUpBonus: "Good credit, business card",
		earningRate: "1.5% cash back",
		bonusCategories: "Simple cash back business card",
		foreignTransactionFees: "",
		interestRate: 0,
	},
	{
		id: 79,
		name: "Bank of America Business Advantage Cash Rewards Mastercard",
		issuer: "BofA",
		rewardType: "",
		annualFee: 0.0,
		signUpBonus: "Good credit, business card",
		earningRate: "1.5% cash back",
		bonusCategories: "Cash back business card",
		foreignTransactionFees: "",
		interestRate: 0,
	},
	{
		id: 80,
		name: "Capital One Spark Miles Select Business Credit Card",
		issuer: "Capital One",
		rewardType: "",
		annualFee: 0.0,
		signUpBonus: "Good credit, business card",
		earningRate: "1x all purchases",
		bonusCategories: "No annual fee business card",
		foreignTransactionFees: "",
		interestRate: 0,
	},
	{
		id: 81,
		name: "Barclaycard Arrival Plus World Elite Mastercard Business Credit Card",
		issuer: "Barclays",
		rewardType: "",
		annualFee: 99.0,
		signUpBonus: "Good credit, business card",
		earningRate: "2x all purchases",
		bonusCategories: "Miles can offset travel purchases",
		foreignTransactionFees: "",
		interestRate: 0,
	},
	{
		id: 82,
		name: "Amazon Prime Rewards Visa Signature",
		issuer: "Chase",
		rewardType: "",
		annualFee: 0.0,
		signUpBonus: "Prime membership required",
		earningRate: "5% Amazon, 2% gas/dining/drugstores",
		bonusCategories: "Must be Amazon Prime member",
		foreignTransactionFees: "",
		interestRate: 0,
	},
	{
		id: 83,
		name: "Amazon Prime Store Card",
		issuer: "Synchrony",
		rewardType: "",
		annualFee: 0.0,
		signUpBonus: "Prime membership required",
		earningRate: "5% Amazon.com",
		bonusCategories: "Must be Amazon Prime member",
		foreignTransactionFees: "",
		interestRate: 0,
	},
	{
		id: 84,
		name: "Amazon Rewards Visa Signature",
		issuer: "Chase",
		rewardType: "",
		annualFee: 0.0,
		signUpBonus: "Amazon account required",
		earningRate: "3% Amazon.com, 2% gas/dining/drugstores",
		bonusCategories: "Must have Amazon account",
		foreignTransactionFees: "",
		interestRate: 0,
	},
	{
		id: 85,
		name: "Amazon Store Card",
		issuer: "Synchrony",
		rewardType: "",
		annualFee: 0.0,
		signUpBonus: "Amazon account required",
		earningRate: "3% Amazon.com",
		bonusCategories: "Must have Amazon account",
		foreignTransactionFees: "",
		interestRate: 0,
	},
]

export default creditCardData
